### ISSUE TITLE
Failed to load the autocomplete-haxe package

### ISSUE THREAD

**Issue by namdq1969** [HaxeIDE/atom-autocomplete-haxe#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-haxe](https://github.com/HaxeIDE/atom-autocomplete-haxe) package, v0.2.0

### Stack Trace

Failed to load the autocomplete-haxe package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/macbookpro/.atom/packages/autocomplete-haxe/node_modules/autocomplete-plus-async/lib/simple-select-list-view.coffee:4:199)
    at /Users/macbookpro/.atom/packages/autocomplete-haxe/node_modules/autocomplete-plus-async/lib/simple-select-list-view.coffee:17:5
    at Object.<anonymous> (/Users/macbookpro/.atom/packages/autocomplete-haxe/node_modules/autocomplete-plus-async/lib/simple-select-list-view.coffee:176:5)
    at Object.<anonymous> (/Users/macbookpro/.atom/packages/autocomplete-haxe/node_modules/autocomplete-plus-async/lib/simple-select-list-view.coffee:180:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.2.4
autocomplete-haxe, v0.2.0
autocomplete-plus, v2.15.2
color-picker, v1.7.0
isotope-ui, v2.2.0
linter, v0.12.2

# Dev
No dev packages
```

**Comment by lucamezzalira** [comment]
+1

**Comment by bloognoo** [comment]
+1 please

**Comment by remogatto** [comment]
+1

**Comment by TerryCavanagh** [comment]
+1

**Comment by lewislepton** [comment]
+1

**Comment by GonzaloCifaldi** [comment]
+1

**Comment by thoughton** [comment]
Just a thought: is this package even in active development any longer, or has it now been superseded by https://atom.io/packages/haxe?

**Comment by remogatto** [comment]
It seems that the atom-haxe package requires this package for completion.

**Comment by thoughton** [comment]
Are you sure? Its page lists the core "autocomplete-plus" package as a dependency, but there's no mention of this "autocomplete-haxe" package listed there.

**Comment by remogatto** [comment]
You're right. Package "atom-haxe" includes autocompletion. Sorry for the noise.

**Comment by thepauljones** [comment]
+1

**Comment by youngmadeof** [comment]
+1

**Comment by ProG4mr** [comment]
+1

**Comment by osca** [comment]
+1

**Comment by vrescobar** [comment]
+1

**Comment by trsh** [comment]
+1

**Comment by st3veV** [comment]
+1

**Comment by trsh** [comment]
On ubuntu same

**Comment by ashes999** [comment]
+1

**Comment by vlad-v** [comment]
+1

**Comment by ambethia** [comment]
Is there a workaround for this yet?

**Comment by ambethia** [comment]
Never mind. I've realized what the earlier commenters meant. Uninstalling this package solves the issue. The plain `haxe` package provides autocompletion.

**Comment by juanfernandoe** [comment]
+1
